config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  root 'calendar#index'
  get 'oauth2callback' => 'authentication#authenticate'
  get 'healthz' => 'health#check_health'
  post 'notify/:conference_room_id' => 'notification#receive', as: :notifications
  get 'admin' => 'admin/conference_rooms#index'

  namespace :admin do
    resources :conference_rooms, except: [:show]
    resources :devices, except: [:show, :create, :new]
  end

  namespace :api do
    resources :calls, only: [:create], defaults: { format: :json }
    resources :conference_rooms, only: [:index], defaults: { format: :json }
    resources :devices, except: [:index, :edit, :new], defaults: { format: :json }
    resources :events, param: :event_id,
                       defaults: { format: :json } do
      member do
        post :confirm
        post :finish
      end
      collection do
        get :confirmed
      end
    end
  end

  resources :conference_rooms, only: [] do
    member do
      get :events, controller: :events, action: :room_index
    end
    resources :events, only: [:update], param: :event_id do
      member do
        post :confirm
        post :finish
      end
    end
  end

  resources :contacts, only: [:index]

  resources :events, only: [:create, :index, :show, :destroy] do
    collection do
      get :confirmed
    end
  end

  resources :conference_rooms, only: [:index, :show], param: :title
end

app/models/conference_room.rb
class ConferenceRoom < ApplicationRecord
  HEX_COLOR_FORMAT = /\A#[0-9a-f]{3}([0-9a-f]{3})?\z/i
  KINDS = {
    narnia: 0,
    without_walls: 1,
    mordor: 2,
    small: 3,
    big: 4
  }.freeze

  enum kind: KINDS

  delegate :channel_id, to: :channel, allow_nil: true

  before_validation { color&.downcase! }
  validates :capacity, presence: true
  validates :color, presence: true, uniqueness: {case_sensitive: false}, format: HEX_COLOR_FORMAT
  validates :title, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_one :channel, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :devices, dependent: :destroy

  scope :without_channel, -> { left_outer_joins(:channel).where(channels: {id: nil}) }

  scope :with_expired_channel, -> { left_outer_joins(:channel).where(channels: {id: Channel.expired}) }

  scope :without_active_channel, -> { without_channel.or with_expired_channel }
end

app/controllers/admin/conference_rooms_controller.rb
module Admin
  class ConferenceRoomsController < Admin::ApplicationController
    before_action :set_admin_conference_room, only: [:edit, :update, :destroy]

    def index
      @rooms = ::ConferenceRoom.all
    end

    def new
      @room = ::ConferenceRoom.new
    end

    def edit
    end

    def create
      @room = ::ConferenceRoom.new(conference_room_params)

      if @room.save
        redirect_to admin_conference_rooms_url, notice: 'Conference room was successfully created.'
      else
        render :new
      end
    end

    def update
      if @room.update(conference_room_params)
        redirect_to admin_conference_rooms_url, notice: 'Conference room was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @room.destroy
      redirect_to admin_conference_rooms_url, notice: 'Conference room was successfully destroyed.'
    end

    private

    def set_admin_conference_room
      @room = ::ConferenceRoom.find(params[:id])
    end

    def conference_room_params
      params.require(:conference_room).permit(:capacity, :color, :title, :email)
    end
  end
end

app/controllers/api/conference_rooms_controller.rb
module Api
  class ConferenceRoomsController < Api::ApplicationController
    def index
      render json: ConferenceRoom.all.to_json(except: [:email, :kind, :logo, :created_at, :updated_at])
    end
  end
end

app/controllers/conference_rooms_controller.rb
class ConferenceRoomsController < ApplicationController
  include GoogleAuthentication
  include GoogleEventClient

  before_action :refresh_token
  before_action :check_authentication

  def show
    create_props
  end

  private

  def create_props
    @props = {active_conference_room: conference_room, all_conference_rooms: ConferenceRoom.all}
  end

  def conference_room
    @conference_room ||= ConferenceRoom.find_by!(title: params[:title].titleize)
  end
end

app/views/admin/conference_rooms/_form.html.erb
<%= form_for([:admin, room]) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this admin_conference_room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/conference_rooms/edit.html.erb
<h1>Editing Conference Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', admin_conference_rooms_path %>

app/views/admin/conference_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conference Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Capacity</th>
      <th>Color</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title -%></td>
        <td><%= room.email -%></td>
        <td><%= room.capacity -%></td>
        <td><%= room.color -%></td>
        <td><%= link_to 'Edit', edit_admin_conference_room_path(room) %></td>
        <td><%= delete_button_to 'Destroy', admin_conference_room_path(room), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference Room', new_admin_conference_room_path %>

app/views/admin/conference_rooms/new.html.erb
<h1>New Conference Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', admin_conference_rooms_path %>