config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'

  root 'calendar#index'
  get 'oauth2callback' => 'authentication#authenticate'
  get 'healthz' => 'health#check_health'
  post 'notify/:conference_room_id' => 'notification#receive', as: :notifications
  get 'admin' => 'admin/conference_rooms#index'

  namespace :admin do
    resources :conference_rooms, except: [:show]
    resources :devices, except: [:show, :create, :new]
  end

  namespace :api do
    resources :calls, only: [:create], defaults: { format: :json }
    resources :conference_rooms, only: [:index], defaults: { format: :json }
    resources :devices, except: [:index, :edit, :new], defaults: { format: :json }
    resources :events, param: :event_id,
                       defaults: { format: :json } do
      member do
        post :confirm
        post :finish
      end
      collection do
        get :confirmed
      end
    end
  end

  resources :conference_rooms, only: [] do
    member do
      get :events, controller: :events, action: :room_index
    end
    resources :events, only: [:update], param: :event_id do
      member do
        post :confirm
        post :finish
      end
    end
  end

  resources :contacts, only: [:index]

  resources :events, only: [:create, :index, :show, :destroy] do
    collection do
      get :confirmed
    end
  end

  resources :conference_rooms, only: [:index, :show], param: :title
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :conference_room

  validates_presence_of :device_id, :device_name
  validates_uniqueness_of :device_id

  scope :authorized, -> { where(authorized: true) }
  scope :sorted, -> { order(updated_at: :desc) }
end

app/controllers/admin/devices_controller.rb
module Admin
  class DevicesController < Admin::ApplicationController
    before_action :set_admin_device, only: [:edit, :update, :destroy]

    def index
      @devices = ::Device.sorted.all
    end

    def edit
    end

    def update
      if @device.update(device_params)
        redirect_to admin_devices_url, notice: 'Device was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @device.destroy
      redirect_to admin_devices_url, notice: 'Device was successfully destroyed.'
    end

    private

    def set_admin_device
      @device = ::Device.find(params[:id])
    end

    def device_params
      params.require(:device).permit(:device_id, :device_name, :conference_room_id, :authorized)
    end
  end
end

app/controllers/api/devices_controller.rb
module Api
  class DevicesController < Api::ApplicationController
    skip_before_action :device_authentication, only: :create
    before_action :set_device, only: [:show, :update, :destroy]

    def show
    end

    def create
      @device = ::Device.find_or_initialize_by(device_params)

      if @device.save
        render json: @device.to_json(only: [:device_id, :device_name,
                                            :authorized, :conference_room_id]), status: :ok
      else
        render json: @device.errors, status: :unprocessable_entity
      end
    end

    def update
      if @device.update(device_params)
        render json: @device.to_json, status: :ok
      else
        render json: @device.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @device.destroy
      head :no_content
    end

    private

    def set_device
      @device = ::Device.find(params[:id])
    end

    def device_params
      params.require(:device).permit(:device_id, :device_name, :conference_room_id)
    end
  end
end

app/views/admin/devices/_form.html.erb
<%= form_for([:admin, device]) do |f| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this admin_device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %>
    <%= f.text_field :device_id %>
  </div>

  <div class="field">
    <%= f.label :device_name %>
    <%= f.text_field :device_name %>
  </div>

  <div class="field">
    <%= f.label :conference_room_id %>
    <%= f.select(:conference_room_id, ConferenceRoom.all.collect { |p| [ p.title, p.id ] }, { include_blank: true }) %>
  </div>

  <div class="field">
    <%= f.label :authorized %>
    <%= f.check_box :authorized %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', admin_devices_path %>

app/views/admin/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Device name</th>
      <th>Conference Room</th>
      <th>Authorized</th>
      <th>Last Change</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.device_id %></td>
        <td><%= device.device_name %></td>
        <td><%= device.conference_room.try(:title) %></td>
        <td><%= device.authorized ? 'Yes' : 'No' %></td>
        <td style="text-align: right">
          <%= device.updated_at -%><br />
          <b><%= distance_of_time_in_words(Time.now, device.updated_at) -%> ago</b>
        </td>
        <td><%= link_to 'Edit', edit_admin_device_path(device) %></td>
        <td><%= delete_button_to 'Destroy', admin_device_path(device), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/devices/new.html.erb
<h1>New Admin Device</h1>

<%= render 'form', admin_device: @admin_device %>

<%= link_to 'Back', admin_devices_path %>